Separate differences by difference, not source.

diff --git a/from_scratch/jenkins-boshrelease-I5H0/packages/fontconfig/packaging b/from_scratch/jenkins-boshrelease-I5H0/packages/fontconfig/packaging
--- a/from_scratch/jenkins-boshrelease-I5H0/packages/fontconfig/packaging
+++ b/from_scratch/jenkins-boshrelease-I5H0/packages/fontconfig/packaging
@@ -1,10 +1,21 @@
-# abort script on any command that exits with a non zero value
-set -e -x -u
 
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
+
+set -x # verbose display of each command
+
+
+export PACKAGE_NAME=$(basename $BOSH_COMPILE_TARGET)
+
+
+# Available variables:
 # $BOSH_INSTALL_TARGET - /var/vcap/packages/$PACKAGE_NAME
 # $BOSH_COMPILE_TARGET - /var/vcap/data/compile/$PACKAGE_NAME
 # $PWD - $BOSH_COMPILE_TARGET
-export PACKAGE_NAME=$(basename $BOSH_COMPILE_TARGET)
+
+# don't use the apt-get install approach as there are tons of problems if foncconfig .deb package is not installed in the standard folders (Cyrille Le Clerc)
+
 
 # install freetype
 tar -xf $PACKAGE_NAME/freetype-2.5.3.tar.bz2
@@ -29,3 +40,4 @@ export LDFLAGS="-L/var/vcap/packages/fontconfig/freetype/lib"
 ./configure --prefix=$BOSH_INSTALL_TARGET --disable-docs --enable-libxml2
 make
 make prefix=$BOSH_INSTALL_TARGET install
+
diff --git a/from_scratch/jenkins-boshrelease-I5H0/packages/jenkins_master_war/packaging b/from_scratch/jenkins-boshrelease-I5H0/packages/jenkins_master_war/packaging
--- a/from_scratch/jenkins-boshrelease-I5H0/packages/jenkins_master_war/packaging
+++ b/from_scratch/jenkins-boshrelease-I5H0/packages/jenkins_master_war/packaging
@@ -1,14 +1,33 @@
-# abort script on any command that exits with a non zero value
-set -e -x -u
+
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
+
+set -x # verbose display of each command
+
+
 
 export PACKAGE_NAME=$(basename $BOSH_COMPILE_TARGET)
 
-# $BOSH_INSTALL_TARGET - /var/vcap/packages/$PACKAGE_NAME
-# $BOSH_COMPILE_TARGET - /var/vcap/data/compile/$PACKAGE_NAME
+
+# Available variables
+# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available (/var/vcap/data/compile/$PACKAGE_NAME)
+# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package (/var/vcap/packages/$PACKAGE_NAME)
+
+
 # $PWD - $BOSH_COMPILE_TARGET
+
+
 
 echo "DEBUG: cd ${BOSH_COMPILE_TARGET}/$PACKAGE_NAME" ;
 cd ${BOSH_COMPILE_TARGET}/$PACKAGE_NAME ;
 archive=`ls -lart | egrep '[.]war$' | tail -1 | awk '{print $NF}'` ;
 
 cp -a $BOSH_COMPILE_TARGET/$PACKAGE_NAME/$archive ${BOSH_INSTALL_TARGET}/jenkins.war
+
+
+
+mkdir -p ${BOSH_INSTALL_TARGET}/plugins
+
+cp /var/vcap/packages/jenkins_plugins/*.* ${BOSH_INSTALL_TARGET}/plugins/ || :  # use  || : to not fail if the directory is empty
+
